variables:
  WEBHOME: "/home/test/deploy/waji/waji-web"

stages:
  - build
  - deploy

build_job:
  stage: build
  script: 
  - echo "git pull..."
  allow_failure: false
  when: manual
   
deploy_job:
  stage: deploy
  script: 
  - mkdir -p ${WEBHOME} 
  - cp -r $PWD/dist/*  ${WEBHOME}
  - ls -l ${WEBHOME} 